INSERT INTO VACINA(nome, data) VALUES('BCG', CURRENT_TIMESTAMP());
INSERT INTO VACINA(nome, data) VALUES('HPV', CURRENT_TIMESTAMP());
INSERT INTO VACINA(nome, data) VALUES('Influenza (Gripe)', CURRENT_TIMESTAMP());